- game.py
Used the module screeninfo to get the monitor resolution of the monitor (1. monitor if there are multiple) and used it to make the game fullscreen.
Note: you have to run "pip install screeninfo" before running the script!
> Changed size of window and elements, so it is displayed in fullscreen.

- game.py
now you have the opportunity after playing a game to choose between playing again and to end the game.
> Added repeat-feture after loosing game

- .github/workflows/github-actions-test.yml
Hier ist die workflow-datei die bei push und pull-request einen flake8 Test über alle **.py datein laufen lässt
> Githubaction

- game.py
Punkte Feature fürs spiel hinzugefügt.
Es Spawnen jetzt nicht nur schwarze sondern auch weiße Rechtecke, diese einzusammeln erhöht einen Punkte counter.
Ist auf dem repeat-feature branch aufgebaut.
> Pointgain feature

- arena.py
Added an Arena class in arena.py with the function paint_arena() which takes two arguments: the instance of pygame and the screen of the pygame initialized with pygame.display.set_mode().
The tiles are stored in the field tiles with help of the enum TileType, which also holds the information of the color of the tiles. 
To find out if there is "ground" on a specific x, y position you have to calculate the tile row and collumn number (for ex. on position x, y = 125, 25 is the tile of row 1 collumn 3) and check if the TileType in the field tiles isn't AIR.
> Implementation of basic Arena

- robot.py
First implementation, might need more functions for later use.
4 Attributes : x and y coordinates, radius r and direction alpha
draw_robot: draws the robot as a blue circle with a black line indicating it's direction
> Implementation of basic robot class

- movement.py
This is the class for the movement of the robot. 
Additional properties can be added here at a later date
> created movement-class

- game.py
Rewrote game.py to run a basic version of the robo arena game using the classes Arena, Robot and Movement. 
I left some of the old cold commented in there to use for later features.
> Rewrote game.py to run a basic version of the robo arena game.

- game.py
Forgot to change way of initializing Arena object in game.py after making changes in arena.py in the arenaBuilder branch.
> Quick fix for game.py not working caused by merging arenaBuilder

- game.py
- movement.py
- robot.py
@ManuShift and I added some simple Bots to the game:
@ManuShift implemented a Start Screen where you can select how many Robots there should be and initialized them accordingly.
I added some logic so that the bots move randomly while you can still controll the first robot by yourself. In doing that, i had to move the vertical_speed variable from the Movement class to the Robot class, so each robot has its own vertical speed.
> Added simple Bots

- arena.py
- game.py
- movement.py
- robot.py
added Block-Physics and Arena borders. Now you can jump on top of the blocks and cant leave the arena
> Block physics

- arena.py
- game.py
- movement.py
- robot.py
Our robot will now change the direction it's facing according to where it is currently moving
> Added rotation to the Robot

- movement.py
Implemented mid air jump: you can now jump twice when in mid air (if you are falling for ex.).
> Implemented mid air jump

- src/game.py
- src/robot.py
Remember when i said that this branch should not have any bugs?
Well i was wrong.
Somehow all Robots share the same projectiles array which wasn't intended, i assume that this is because of the append command doing some weird things with arrays.
This resulted in all projectiles being updated as many times as there are robots (per frame) when every projectile should be updated just once (per frame).
This fix did not adress the isssue of all robots sharing this array but it did make the update selective so projectiles will no longer be faster if multiple bots exist.
> Ranged_attack bug fix

- src/game.py
- src/projectiles.py
- src/robot.py
Even though the branch is named melee_changes i chose to also do the ranged changes on this branch.
For now i refactored the cooldown a little, added damage values to all projectiles and reworked our basic melee attack, before we had a stab and now we have a swing.
Next i want to add a big projectile that moves slower and "expoldes" on impact.
Followed by a heavy melee attack that will do more damage and ideally knockback, and will make the robot who attacked unable to move while charging this heavy attack
> Melee and Ranged changes

- src/arena.py
- src/game.py
- src/movement.py
- src/robot.py
Changed Tiles in order to Track what kind of Tile we stand on/ touch.
Touching is for now only relevant for lava tiles, we take damage if we touch a lava tile no matter from which direction.
We track if whether or not we stand on either, lava, ice sand or none of these.
We can use this to change our speed and acceleration changes depending on which tile we stand on, which I plan to do soon.
We could also make it more difficult to jump from certain tiles, removing jumpheight but I will not do that for now.
> Tilechanges

- src/game.py
While merging i did not remember to change the attack functions for the controler, so they were broken.
Sadly i don't know what other possible options there are and can't properly assign the Heavy and explosive attacks to different buttons.
As such I have not attempted this yet and will likely only hav time to read into this after monday.
I also removed one line of dead code I found which caused a crash when changing resolution.
But I also removed it from main during the merge with Tilechanges
> Controler attack fix

- src/game.py
- src/projectiles.py
- src/robot.py
Completely ignoring everything we learned in SE i made all changes in one single commit.
New bouncy projectiles for now bound to the z key, they will bounce twice before deissapearing like all other projectiles, however we don't bounce off robots although that can be changed easily.
> added bouncy projectile

- src/game.py
- src/robot.py
Added a flamthrower attack currently bound to k
The attack is most simmilar to the laser but it's much slimmer and shorter with the flame fanning out towards the end of the attack.
This fanning out goes upwards if we attack to the left or right and if we shoot upwards or downwards it will fan out both to the left and right,
> Flamethrower

- src/game.py
- src/robot.py
I have once again disregared all we have learned in SE and made all changes in one single commit.
I created a laser attack that will stop after a max range or if we hit a block / the arena boundary whichever is closest to the robot.
For now it is bound to u and the area of the laser is shown by a rectangle with red outlines for now.
> added new ranged attack a laser

- src/game.py
- src/robot.py
Using our first melee attack as a base i created a somewhat more interesting version of it, it is currently bound to j.
We have multiple stab attacks per button press starting with one central stab and then a stab 30° above and then 30° below it and finish with another central stab.
Each stab has 2 stages starting in a shorter form for 5 frames , then transitioning into a slightly longer version for another 5 frames.
This looks a bit weird currently and i will try to make this more noticable later.
This attack also has effectivly no cooldown when the stab finishes we can immediatly attack again.
> New stab like melee attack

- src/game.py
You can now move the robot with WASD and turn your viewing direction with the arrow keys/right joystick.
Could be nice to make aiming more variable, but It stresses me a little bit when trying to attack.
Should we keep that or disregard these controls?
> Changed controls
